version: 2
updates:
  # Enable version updates for Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@me"
    assignees:
      - "@me"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      # Group security-related dependencies
      security:
        patterns:
          - "openssl*"
          - "rustls*"
          - "webpki*"
          - "ring"
      # Group development dependencies
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      # Group testing dependencies
      testing:
        patterns:
          - "mockall*"
          - "tempfile"
          - "assert*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "@me"
    assignees:
      - "@me"
    commit-message:
      prefix: "ci"
      include: "scope"
